=== itnifl/DiskReporter/DiskReporter/bin/Debug/config_TSMServers.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:annotation>
	<xsd:documentation>TSM Server Configuration</xsd:documentation>
</xsd:annotation>

<xsd:element name="configContents">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="SERVER" type="serverConfig" maxOccurs="*" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>


<xsd:complexType name="serverConfig">
	<xsd:sequence>
		<xsd:element name="ADDRESS" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="NAME" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="USER" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="PASSWORD" type="xsd:string" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== itnifl/DiskReporter/config&Dependencies/config_TSMServers.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<configContents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config_TSMServers.xsd">
	<SERVER>
		<ADDRESS>8.8.8.8</ADDRESS>
		<NAME>TSM01</NAME>
		<USER>tsmChatter</USER>
		<PASSWORD>Pass123</PASSWORD>
	</SERVER>
	<SERVER>
		<ADDRESS>8.8.8.9</ADDRESS>
		<NAME>TSM02</NAME>
		<USER>tsmChatter</USER>
		<PASSWORD>Pass123</PASSWORD>
	</SERVER>
</configContents>
